In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.DataFrame(columns = ['Student'])
df

Empty DataFrame
Columns: [Student]
Index: []

In [3]:
def alphaB(strng):
    global df
    if(len(df)>=1):
        dfNew = pd.DataFrame(columns = df.keys())
        dfNew.loc[0] = " "
        dfNew.loc[0]['Student'] = strng 
        df = pd.concat([df, dfNew])
        df.reset_index(drop = True, inplace = True)
    else:
        df.loc[0] = " "
        df.loc[0]['Student'] = strng

In [4]:
def updateTest(strng):
    nameS = input("Enter the name of the student whos score you wish to add:")
    score = input("Enter the score of the test: ")
    indx = df[df['Student'] == nameS].index
    df.at[indx, strng] = int(score) # set_value doesnt work anymore

In [5]:
def removeT(strng):
    df.drop([strng], axis = 1, inplace = True)

In [6]:
def removeS(strng):
    indx = df[df['Student'] == strng].index
    df.drop(indx, inplace = True)

In [7]:
#add test column

def newTest(strng):
    df[strng] = " "

In [8]:
def add(numero):
    while(numero != 0):
        if(numero == 1):
            name = input("Enter the name of the student you wish to add: ") 
            alphaB(name)
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
        if(numero == 2):
            name = input("Enter the name of the test you wish to add: ")
            newTest(name)
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
        if(numero == 3):
            name = input("Enter the name of the test whos score you wish to update: ")
            updateTest(name)
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
        if(numero == 4):
            print(df)
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
        if(numero == 5):
            name = input("Enter the name of the test you wish to find the average of: ")
            print('The average is: ', df[name].mean())
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
        if(numero == 6):
            name = input("Enter the name of the test you wish to drop: ")
            removeT(name)
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
        if(numero == 7):
            name = input("Enter the name of the student you wish to drop: ")
            removeS(name)
            print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
            numero = int(input())
    print('Canceled')

In [9]:
print("Input: \n 1) to add a student to the gradebook \n 2) to add a new test \n 3) to update a test score \n 4) to view the grade book \n 5) to find a test's average \n 6) to drop a test \n 7) to drop a student \n 0) to quit ")
n = int(input())
add(n)
df

Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
1
Enter the name of the student you wish to add: Jess
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
1
Enter the name of the student you wish to add: Josh
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
1
Enter the name of the student you wish to add: Andrew
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
2
Enter the name of the test you wish to add: Test 1
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
2
Enter the name of the test you wish to add: Test 2
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
3
Enter the name of the test whos score you wish to update: Test 1
Enter the name of the student whos score you wish to add:Jess
Enter the score of the test: 94
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
3
Enter the name of the test whos score you wish to update: Test 1
Enter the name of the student whos score you wish to add:Josh
Enter the score of the test: 93
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
3
Enter the name of the test whos score you wish to update: Test 1
Enter the name of the student whos score you wish to add:Andrew
Enter the score of the test: 92
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
4
  Student Test 1 Test 2
0    Jess     94
1    Josh     93
2  Andrew     92
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
5
Enter the name of the test you wish to find the average of: Test 1
The average is:  93.0
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
6
Enter the name of the test you wish to drop: Test 2
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
4
  Student Test 1
0    Jess     94
1    Josh     93
2  Andrew     92
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
7
Enter the name of the student you wish to drop: Andrew
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
4
  Student Test 1
0    Jess     94
1    Josh     93
Input:
 1) to add a student to the gradebook
 2) to add a new test
 3) to update a test score
 4) to view the grade book
 5) to find a test's average
 6) to drop a test
 7) to drop a student
 0) to quit
0
Canceled

  Student Test 1
0    Jess     94
1    Josh     93

In [12]:
# with more time I would:
## show the averages of each student
## allow for quizzes and tests to be weighted differently
## give the ability to add curves to grades